site_name: eBPF Docs

repo_url: https://github.com/isovalent/ebpf-docs
edit_uri: blob/master/docs/

theme:
  name: material
  logo: assets/image/logo.png
  favicon: assets/image/favicon-32x32.png
  features:
    - navigation.indexes
    - navigation.top
    - content.action.view
    - content.action.edit
  font:
    text: Inter
    code: Inter
  palette:
    scheme: slate
    primary: yellow
    accent: amber

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

  custom_dir: overwrites

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - abbr
  - pymdownx.snippets

plugins:
  - search:
      lang: en
      separator: '[\s\-\_\.]+'
  - literate-nav:
      nav-file: SUMMARY.md
      tab_length: 2

extra_css:
  - stylesheets/extra.css
