site_name: eBPF Docs

theme:
  name: material
  logo: assets/image/logo.png
  favicon: assets/image/favicon-32x32.png
  features:
    - navigation.indexes
  font:
    text: Inter
    code: Inter
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - abbr
  - pymdownx.snippets

plugins:
  - search:
      lang: en
      separator: '[\s\-\_\.]+'

nav:
  - Home: index.md
  - Concepts: concepts/index.md
  - Linux Reference: 
    - linux/index.md
    - Concepts: linux/ebpf-concepts/index.md
    - Syscall commands: linux/syscall/index.md
    - Program types: linux/program-type/index.md
    - Map types: linux/map-type/index.md
    - Helper functions: linux/helper-function/index.md
  - Libraries: ebpf-library/index.md
    