name: Spellcheck

on:
  pull_request: {}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  USER: root

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run spellcheck
        run: |
          make spellcheck

